import type { Metadata } from 'next'
import './globals.css'
import { oswald } from './fonts'
import type { Viewport } from "next";

export const viewport: Viewport = {
  themeColor: [
    { media: '(prefers-color-scheme: light)', color: '#f1f6fb' },
    { media: '(prefers-color-scheme: dark)', color: '#262626' },
  ],
}

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body className={` ${oswald.className} bg-[#f1f6fb] dark:bg-[#262626]`}>
        {children}
      </body>
    </html>
  )
}
