import Cursor from '@/components/Cursor'
import { ChevronUpIcon } from '@heroicons/react/24/solid'
import { BackToTop } from 'aspect-ui/BackToTop'
import type { Metadata } from 'next'
import { oswald } from './fonts'
import './globals.css'


export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body className={` ${oswald.className} bg-[#f1f6fb] dark:bg-[#262626]`}>
        <Cursor />
        {children}
        <BackToTop className="p-2 border border-primaryColor bg-primaryColor bg-opacity-10
text-primaryColor backdrop-blur-xl">
          <ChevronUpIcon className='w-6' />
        </BackToTop>
      </body>
    </html>
  )
}
